baseURL = 'https://mango-sky-01400dd03.4.azurestaticapps.net/'
languageCode = 'en-us'
title = 'quas wex exort'
theme = 'mod-Papermod'

[[menu.main]]
identifier = "about me"
name = "about me"
url = "about-me/"
weight = 5

[[menu.main]]
identifier = "resume"
name = "resume"
url = "resume/"
weight = 10

[markup.goldmark.renderer]
unsafe= true